# -*- coding: utf-8 -*-
"""USinflationplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gil6Nta08yVsNCd8QOQ0kKIh3WCCabt

# Inflation plot w/ API from BLS

## Main execution
"""

# Commented out IPython magic to ensure Python compatibility.
import requests
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
import os
import matplotlib.ticker as mticker

# Always reset directory before shell commands
# %cd /content

# Set Git identity for this Colab session
!git config --global user.email "lenz.eric@gmail.com"
!git config --global user.name "lenzeric"

# ========== BLS CPI Inflation Plot ==========
# BLS API key
API_KEY = 'f835522d726c44f3bc36936bd1e1c571'
SERIES_ID = 'CUSR0000SA0' # CPI for All Urban Consumers (All Items)

# ---- Step 1: Fetch data ----
all_data = []
for year in range(2000, datetime.now().year + 1):
    payload = {
        "seriesid": [SERIES_ID],
        "startyear": str(year),
        "endyear": str(year),
        "registrationKey": API_KEY
    }
    response = requests.post("https://api.bls.gov/publicAPI/v2/timeseries/data/", json=payload)
    response.raise_for_status()
    data = response.json()
    try:
        chunk = data['Results']['series'][0]['data']
        all_data.extend(chunk)
    except KeyError:
        print(f"No data for {year}")

# ---- Step 2: Create DataFrame ----
df = pd.DataFrame(all_data)
df = df[df['period'].str.startswith('M')]
df['value'] = pd.to_numeric(df['value'])
df['date'] = pd.to_datetime(df['year'] + df['period'].str[1:], format='%Y%m')
df = df.sort_values('date')
df['yoy_inflation'] = df['value'].pct_change(12) * 100

max_inflation = df['yoy_inflation'].max()
df = df[df['date'] >= pd.to_datetime("2000-01-01")]

# ---- Step 3: Presidential terms ----
presidents = [
    {'name': 'Bush',   'start': '2001-01-20', 'end': '2009-01-20', 'color': 'red'},
    {'name': 'Obama',  'start': '2009-01-20', 'end': '2017-01-20', 'color': 'blue'},
    {'name': 'Trump',  'start': '2017-01-20', 'end': '2021-01-20', 'color': 'red'},
    {'name': 'Biden',  'start': '2021-01-20', 'end': '2025-01-20', 'color': 'blue'},
    {'name': 'Trump',  'start': '2025-01-20', 'end': df['date'].max(), 'color': 'red'}
]

# ---- Step 4: Plot ----
fig, ax = plt.subplots(figsize=(12, 6))

for term in presidents:
    start, end = pd.to_datetime(term['start']), pd.to_datetime(term['end'])
    mask = (df['date'] >= start) & (df['date'] <= end)
    avg_inflation = df.loc[mask, 'yoy_inflation'].mean()
    ax.axvspan(start, end, color=term['color'], alpha=0.1)

    label_x = start + (end - start) / 2
    bottom, _ = ax.get_ylim()
    ax.text(label_x, bottom - 0.45, f"{term['name']}\n{avg_inflation:.2f}%",
            ha='center', va='bottom', fontsize=9, color=term['color'],
            bbox=dict(facecolor='white', edgecolor='none', alpha=0.6))

ax.plot(df['date'], df['yoy_inflation'], label='12-Month Inflation Rate', color='black')
ax.axhline(2, color='green', linestyle='--', label='2% Target')

ax.set_title("12-Month CPI Inflation with Presidential Terms and Averages")
ax.set_ylabel("Year-over-Year % Change")
ax.set_xlabel("Date")
ax.legend()

ax.xaxis.set_major_locator(mdates.YearLocator(2))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
ax.set_ylim(-2, max(8, max_inflation + 1))

plt.tight_layout()
plt.savefig("inflation_plot.png", bbox_inches="tight", dpi=300)
plt.show()
print("✅ Saved inflation_plot.png")
