name: Auto Update Inflation Plots

on:
  schedule:
    - cron: "0 12 * * 1"   # Every Monday at 12:00 UTC
  workflow_dispatch:        # Allow manual runs from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run update script
      run: python update_plots.py

    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.png
        git commit -m "Auto update plots [skip ci]" || echo "No changes to commit"
        git push
